-- Create table for Contact Form messages
create table if not exists contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create table for Write for Wim applications
create table if not exists wim_applications (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  portfolio_url text,
  pitch text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table contact_messages enable row level security;
alter table wim_applications enable row level security;

-- Policies: Allow anyone to insert (submit forms), but only admin can view (in theory, though we haven't built admin view for this yet)
create policy "Allow public inserts for contact_messages" 
on contact_messages for insert 
with check (true);

create policy "Allow public inserts for wim_applications" 
on wim_applications for insert 
with check (true);

-- Optional: Allow read access only to authenticated users (admins) if you implement viewing later
-- create policy "Allow read access to admins" on contact_messages for select using (auth.role() = 'authenticated');
