-- BU DOSYADAKİ TÜM KODU KOPYALA VE SUPABASE "SQL EDITOR" EKRANINA YAPIŞTIRIP "RUN" BUTONUNA BAS --

-- 1. PROFİLLER TABLOSU (Kullanıcı hesapları için)
create table profiles (
  id uuid references auth.users not null,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,
  website text,
  primary key (id),
  unique(username),
  constraint username_length check (char_length(username) >= 3)
);

-- Güvenlik Kuralları (RLS)
alter table profiles enable row level security;

create policy "Herkes profilleri görebilir" on profiles for select using ( true );
create policy "Kullanıcılar kendi profilini ekleyebilir" on profiles for insert with check ( auth.uid() = id );
create policy "Kullanıcılar kendi profilini güncelleyebilir" on profiles for update using ( auth.uid() = id );

-- Otomatik Profil Oluşturucu (Yeni üye kaydolduğunda çalışır)
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (
    new.id, 
    new.raw_user_meta_data->>'username', 
    'https://i.pravatar.cc/150?u=' || new.id
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. YORUMLAR TABLOSU
create table comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  post_id text not null, -- Hangi blog yazısı olduğu
  user_id uuid references profiles(id) not null,
  parent_id bigint references comments(id) -- Cevap verilen yorum (varsa)
);

alter table comments enable row level security;

create policy "Herkes yorumları görebilir" on comments for select using ( true );
create policy "Giriş yapmış kullanıcılar yorum atabilir" on comments for insert with check ( auth.role() = 'authenticated' );
