-- BU DOSYAYI SUPABASE SQL EDITOR'ÜNDE ÇALIŞTIRIN
-- Bu komutlar veritabanını onarır, eksik tabloları oluşturur ve yeni üye kaydını garanti altına alır.

-- 1. PROFILES TABLOSUNU GARANTİLE
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,
  website text
);

-- 2. ROLE KOLONUNU EKLE (Eksikse)
alter table public.profiles add column if not exists role text default 'user';

-- 3. GÜVENLİK (RLS) AYARLARI
alter table public.profiles enable row level security;

-- Mevcut politikaları temizle (Hata vermemesi için drop if exists)
drop policy if exists "Public profiles" on public.profiles;
drop policy if exists "Herkes profilleri görebilir" on public.profiles;
drop policy if exists "Self insert" on public.profiles;
drop policy if exists "Kullanıcılar kendi profilini ekleyebilir" on public.profiles;
drop policy if exists "Self update" on public.profiles;
drop policy if exists "Kullanıcılar kendi profilini güncelleyebilir" on public.profiles;

-- Politikaları yeniden oluştur
create policy "Public profiles" on public.profiles for select using (true);
create policy "Self insert" on public.profiles for insert with check (auth.uid() = id);
create policy "Self update" on public.profiles for update using (auth.uid() = id);

-- 4. KISITLAMALARI GEVŞET (Login sorunlarını önlemek için)
-- 3 karakter sınırını kaldırıyoruz çünkü bazı emailler kısa olabilir (örn: ab@domain.com -> ab)
alter table public.profiles drop constraint if exists username_length;

-- 5. GELİŞMİŞ YENİ ÜYE TRIGGER'I (Hatasız Kayıt İçin)
create or replace function public.handle_new_user() 
returns trigger as $$
declare
  raw_username text;
  final_username text;
begin
  -- 1. Username Adayı Belirleme
  -- Metadata varsa al, yoksa email'in baş kısmını al
  raw_username := new.raw_user_meta_data->>'username';
  if raw_username is null or length(raw_username) = 0 then
    raw_username := split_part(new.email, '@', 1);
  end if;
  
  -- 2. Username Temizleme ve Formatlama
  -- Eğer hala boşsa veya çok kısaysa ID'den üret
  if raw_username is null or length(raw_username) < 2 then
     final_username := 'user_' || substr(new.id::text, 1, 8);
  else
     final_username := raw_username;
  end if;

  -- 3. Kayıt (Conflict Handling ile)
  begin
    insert into public.profiles (id, username, avatar_url, role)
    values (
      new.id, 
      final_username, 
      'https://i.pravatar.cc/150?u=' || new.id,
      'user'
    );
  exception when unique_violation then
    -- Eğer username doluysa, sonuna rastgele sayı ekleyip tekrar dene
    insert into public.profiles (id, username, avatar_url, role)
    values (
      new.id, 
      final_username || '_' || substr(md5(random()::text), 1, 4), 
      'https://i.pravatar.cc/150?u=' || new.id,
      'user'
    );
  end;
  
  return new;
end;
$$ language plpgsql security definer;

-- Trigger'ı yeniden bağla
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 6. YORUMLAR TABLOSU (Eksikse)
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  post_id text not null,
  user_id uuid references public.profiles(id) not null,
  parent_id bigint references public.comments(id)
);
alter table public.comments enable row level security;
drop policy if exists "Public comments" on public.comments;
create policy "Public comments" on public.comments for select using (true);
drop policy if exists "Authenticated insert comments" on public.comments;
create policy "Authenticated insert comments" on public.comments for insert with check (auth.role() = 'authenticated');

-- 7. BLOG YAZILARI TABLOSU (Eksikse)
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text not null,
  slug text,
  author text not null,
  category text default 'uncategorized',
  published boolean default true
);
alter table public.posts enable row level security;
drop policy if exists "Public posts" on public.posts;
create policy "Public posts" on public.posts for select using ( published = true );
