-- ================================================================
-- WORLDINMAKING - MASTER SETUP SCRIPT
-- ================================================================
-- Bu dosya tüm proje veritabanını tek seferde kurmak için hazırlanmıştır.
-- Kullanımı: 
-- 1. Supabase Dashboard -> Database -> Reset Database (Tüm verileri siler)
-- 2. SQL Editor -> Bu dosyanın tamamını yapıştır ve RUN'a bas. 

-- ================================================================
-- 1. PROFİL VE KULLANICI SİSTEMİ
-- ================================================================

-- Profil Tablosu
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,
  website text,
  role text default 'user' -- 'admin' veya 'user'
);

-- RLS (Güvenlik) - Profiles
alter table public.profiles enable row level security;
drop policy if exists "Public profiles" on public.profiles;
create policy "Public profiles" on public.profiles for select using (true);

drop policy if exists "Self insert" on public.profiles;
create policy "Self insert" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "Self update" on public.profiles;
create policy "Self update" on public.profiles for update using (auth.uid() = id);

-- Constraint Temizliği (Kısa emaillerin sorun çıkarmaması için)
alter table public.profiles drop constraint if exists username_length;

-- Profil Oluşturma Trigger (Güvenli ve Hatasız Kayıt İçin)
create or replace function public.handle_new_user() 
returns trigger as $$
declare
  raw_username text;
  final_username text;
begin
  -- Email veya Metadata'dan Username Belirle
  raw_username := new.raw_user_meta_data->>'username';
  if raw_username is null or length(raw_username) = 0 then
    raw_username := split_part(new.email, '@', 1);
  end if;
  
  -- Çok kısaysa ID kullan
  if raw_username is null or length(raw_username) < 2 then
     final_username := 'user_' || substr(new.id::text, 1, 8);
  else
     final_username := raw_username;
  end if;

  -- Kayıt oluştur (Çakışma durumunda da çalışır)
  begin
    insert into public.profiles (id, username, avatar_url, role)
    values (
      new.id, 
      final_username, 
      'https://i.pravatar.cc/150?u=' || new.id,
      'user'
    );
  exception when unique_violation then
    insert into public.profiles (id, username, avatar_url, role)
    values (
      new.id, 
      final_username || '_' || substr(md5(random()::text), 1, 4), 
      'https://i.pravatar.cc/150?u=' || new.id,
      'user'
    );
  end;
  return new;
end;
$$ language plpgsql security definer;

-- Trigger Bağlantısı
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- ================================================================
-- 2. İÇERİK YÖNETİMİ (BLOG, YORUM, BEĞENİ)
-- ================================================================

-- Blog Yazıları (Posts)
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text not null,
  excerpt text,
  slug text,
  author text not null,
  author_avatar text,
  category text default 'uncategorized',
  published boolean default true
);

alter table public.posts enable row level security;
drop policy if exists "Herkes yazıları görebilir" on public.posts;
create policy "Herkes yazıları görebilir" on public.posts for select using ( published = true );

drop policy if exists "Sadece adminler yazı yönetebilir" on public.posts;
create policy "Sadece adminler yazı yönetebilir" on public.posts for all using ( 
  exists ( select 1 from public.profiles where id = auth.uid() and role = 'admin' ) 
);


-- Yorumlar (Comments)
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  post_id text not null,
  user_id uuid references public.profiles(id) not null,
  parent_id bigint references public.comments(id)
);

alter table public.comments enable row level security;
drop policy if exists "Herkes yorumları görebilir" on public.comments;
create policy "Herkes yorumları görebilir" on public.comments for select using (true);

drop policy if exists "Giriş yapmış kullanıcı yorum atabilir" on public.comments;
create policy "Giriş yapmış kullanıcı yorum atabilir" on public.comments for insert with check (auth.role() = 'authenticated');

drop policy if exists "Admin yorum silebilir" on public.comments;
create policy "Admin yorum silebilir" on public.comments for delete using ( 
    exists ( select 1 from public.profiles where id = auth.uid() and role = 'admin' ) 
);


-- Beğeniler (Likes)
create table if not exists public.post_likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  post_id text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, post_id)
);

alter table public.post_likes enable row level security;
drop policy if exists "Herkes beğenileri görebilir" on public.post_likes;
create policy "Herkes beğenileri görebilir" on public.post_likes for select using (true);

drop policy if exists "Üyeler beğeni atabilir" on public.post_likes;
create policy "Üyeler beğeni atabilir" on public.post_likes for insert with check (auth.uid() = user_id);

drop policy if exists "Üyeler beğenisini geri alabilir" on public.post_likes;
create policy "Üyeler beğenisini geri alabilir" on public.post_likes for delete using (auth.uid() = user_id);


-- ================================================================
-- 3. FORM VE BAŞVURU SİSTEMİ
-- ================================================================

-- İletişim Formları
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.contact_messages enable row level security;
drop policy if exists "Public insert contact" on public.contact_messages;
create policy "Public insert contact" on public.contact_messages for insert with check (true);
-- Admin okuma izni de eklenebilir:
-- create policy "Admin read contact" on public.contact_messages for select using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));


-- Yazar Başvuruları (Write for Wim)
create table if not exists public.wim_applications (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  portfolio_url text,
  pitch text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.wim_applications enable row level security;
drop policy if exists "Public insert application" on public.wim_applications;
create policy "Public insert application" on public.wim_applications for insert with check (true);


-- ================================================================
-- 4. STORAGE (DOSYA DEPOLAMA)
-- ================================================================

insert into storage.buckets (id, name, public) 
values ('blog-images', 'blog-images', true)
on conflict (id) do nothing;

drop policy if exists "Resimler herkese açık" on storage.objects;
create policy "Resimler herkese açık" on storage.objects for select using ( bucket_id = 'blog-images' );

drop policy if exists "Admin resim yükleyebilir" on storage.objects;
create policy "Admin resim yükleyebilir" on storage.objects for insert with check (
  bucket_id = 'blog-images' and 
  exists ( select 1 from public.profiles where id = auth.uid() and role = 'admin' )
);


-- ================================================================
-- 5. VARSAYILAN ADMİN ATAMA
-- ================================================================
-- Eğer listelenen kullanıcı kayıtlıysa rolünü 'admin' yap.
update public.profiles
set role = 'admin'
where id in (
  select id from auth.users where email in ('dursunkayamustafa@gmail.com')
);

-- ================================================================
-- KURULUM TAMAMLANDI.
-- ================================================================
