-- BU KODU SUPABASE SQL EDITOR'DE ÇALIŞTIR --

-- 1. Kullanıcılara 'rol' özelliği ekle (user / admin)
alter table profiles add column if not exists role text default 'user';

-- 2. Blog Yazıları Tablosu (Artık yazılar veritabanında duracak)
create table if not exists posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text not null, -- Yazı içeriği (HTML)
  excerpt text, -- Kısa özet
  slug text, -- URL için (örn: neden-dunya-boyle)
  author text not null, -- Yazar adı (İstediğin ismi verebilirsin)
  author_avatar text, -- Yazar resmi URL
  category text default 'uncategorized',
  published boolean default true
);

-- Güvenlik Kuralları (RLS)
alter table posts enable row level security;

-- Herkes yayınlanmış yazıları görebilir
create policy "Public posts are viewable by everyone" 
on posts for select 
using ( published = true );

-- Sadece 'admin' rolüne sahip olanlar yazı ekleyebilir/düzenleyebilir/silebilir
create policy "Admins can manage posts" 
on posts for all 
using ( 
  exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) 
);

-- Admin, yorumları da silebilir
create policy "Admins can delete comments" 
on comments for delete 
using ( 
  exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) 
);

-- 3. ÖZEL İŞLEM: Spesifik Kullanıcıyı Admin Yap
-- Not: Bu komutun işlemesi için kullanıcının en az 1 kere siteye giriş yapmış olması gerekir.
update profiles
set role = 'admin'
where id in (
  select id from auth.users where email = 'dursunkayamustafa@gmail.com'
);
