-- BU KODU SUPABASE SQL EDITOR'DE ÇALIŞTIR --

-- 1. Beğeni (Like) Sistemi Tablosu
create table if not exists post_likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  post_id text not null, -- Blog yazısının ID'si (Slug veya ID)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, post_id) -- Aynı kullanıcı aynı yazıyı sadece bir kez beğenebilir
);

-- Güvenlik (RLS)
alter table post_likes enable row level security;

-- Herkes beğenileri görebilir (Sayısını saymak için)
create policy "Likes are public" 
on post_likes for select 
using ( true );

-- Giriş yapmış kullanıcı beğeni atabilir
create policy "Users can like posts" 
on post_likes for insert 
with check ( auth.uid() = user_id );

-- Kullanıcı sadece kendi beğenesini geri alabilir (Unlike)
create policy "Users can unlike posts" 
on post_likes for delete 
using ( auth.uid() = user_id );
